//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalExam_1931358
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbFinalExam_1931358Entities : DbContext
    {
        public dbFinalExam_1931358Entities()
            : base("name=dbFinalExam_1931358Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<url> urls { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<log> logs { get; set; }
    }
}
